title = "Website Name"
baseURL = 'https://rooksword.github.io/tutoring-website/'
languageCode = 'en-us'

[params]
  google_fonts = [
    ["Fira Code", "400, 700"],
    ["Open Sans", "400, 400i, 700, 700i"]
  ]

  heading_font = "Fira Code"
  body_font = "Open Sans"

  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'